#!/usr/bin/env python3
"""Generate tool-specific AI instruction adapters from .ai/.

Run: python scripts/sync_skills.py

Generates full skill, role, and workflow adapters for Claude Code, Cursor, and
Codex. .ai/ is the single source of truth; edit canonical files there and then
run `make sync-ai`.

Adapter locations:
  .claude/skills/<name>/SKILL.md
  .claude/agents/<name>.md
  .claude/workflows/<name>.md
  .cursor/rules/skills/<name>.mdc
  .cursor/rules/roles/<name>.mdc
  .cursor/rules/workflows/<name>.mdc
  .codex/skills/<name>.md
  .codex/agents/<name>.md
  .codex/workflows/<name>.md
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).parent.parent

FRONTMATTER_RE = re.compile(r"^---\n(.*?)\n---(?:\n|$)", re.DOTALL)

FALLBACK_DESCRIPTION = "Use this {kind} for {name} related work."

GENERATED_COMMENT = """\
<!--
This file is generated by scripts/sync_skills.py.
Do not edit this file directly.
Edit .ai/{source_kind}/{name}.md and run `make sync-ai`.
-->
"""

MARKDOWN_HEADER = """\
---
name: {name}
description: {description}
generated: true
source: .ai/{source_kind}/{name}.md
---
"""

CURSOR_HEADER = """\
---
description: {description}
alwaysApply: false
generated: true
source: .ai/{source_kind}/{name}.md
---
"""

SOURCE_KINDS: dict[str, str] = {
    "skills": "skill",
    "roles": "role",
    "workflows": "workflow",
}


def parse_frontmatter_block(block: str) -> dict[str, object]:
    """Parse the simple YAML frontmatter used by canonical instruction files."""
    fields: dict[str, object] = {}
    for line in block.splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#") or ":" not in stripped:
            continue
        key, _, raw_value = stripped.partition(":")
        key = key.strip()
        value = raw_value.strip()
        if not key:
            continue

        if (value.startswith('"') and value.endswith('"')) or (
            value.startswith("'") and value.endswith("'")
        ):
            value = value[1:-1]

        lowered = value.lower()
        if lowered == "true":
            fields[key] = True
        elif lowered == "false":
            fields[key] = False
        else:
            fields[key] = value

    return fields


def split_instruction_content(text: str) -> tuple[dict[str, object], str]:
    """Return frontmatter fields and body without source frontmatter."""
    match = FRONTMATTER_RE.match(text)
    if not match:
        return {}, text

    fields = parse_frontmatter_block(match.group(1))
    body = text[match.end() :]
    if body.startswith("\n"):
        body = body[1:]
    return fields, body


# Backward-compatible helper name used by existing tests and older callers.
split_skill_content = split_instruction_content


def read_source_instruction(path: Path, *, kind: str) -> tuple[str, str, str]:
    """Return name, description, and body for a canonical instruction file."""
    text = path.read_text()
    fields, body = split_instruction_content(text)
    name = str(fields.get("name") or path.stem)
    description = str(
        fields.get("description") or FALLBACK_DESCRIPTION.format(kind=kind, name=name)
    )
    return name, description, body


def parse_frontmatter(text: str) -> dict[str, object]:
    match = FRONTMATTER_RE.match(text)
    if not match:
        return {}
    return parse_frontmatter_block(match.group(1))


def is_generated(path: Path) -> bool:
    try:
        generated = parse_frontmatter(path.read_text()).get("generated")
    except OSError:
        return False

    if generated is True:
        return True
    return isinstance(generated, str) and generated.lower() == "true"


def yaml_scalar(value: str) -> str:
    """Return a YAML-safe scalar for frontmatter fields."""
    if not value:
        return '""'
    if re.search(r'[:#\[\]{}"\'\\,&*!|>%@`]', value) or value.strip() != value:
        escaped = value.replace("\\", "\\\\").replace('"', '\\"')
        return f'"{escaped}"'
    return value


def build_adapter(
    header: str,
    *,
    name: str,
    description: str,
    body: str,
    source_kind: str,
) -> str:
    comment = GENERATED_COMMENT.format(name=name, source_kind=source_kind)
    rendered_header = header.format(
        name=name,
        description=yaml_scalar(description),
        source_kind=source_kind,
    )
    if body:
        return f"{rendered_header}\n{comment}\n{body}"
    return f"{rendered_header}\n{comment}\n"


def write_adapter(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content)


def claude_adapter_path(root: Path, source_kind: str, name: str) -> Path:
    if source_kind == "skills":
        return root / ".claude" / "skills" / name / "SKILL.md"
    if source_kind == "roles":
        return root / ".claude" / "agents" / f"{name}.md"
    return root / ".claude" / "workflows" / f"{name}.md"


def codex_adapter_dir(source_kind: str) -> str:
    if source_kind == "roles":
        return "agents"
    return source_kind


def generate_adapters(root: Path, *, generated: list[Path]) -> dict[str, set[str]]:
    source_names_by_kind: dict[str, set[str]] = {}

    for source_kind, kind_label in SOURCE_KINDS.items():
        source_dir = root / ".ai" / source_kind
        source_names: set[str] = set()

        for source_file in sorted(source_dir.glob("*.md")):
            name, description, body = read_source_instruction(
                source_file,
                kind=kind_label,
            )
            source_names.add(name)

            claude_path = claude_adapter_path(root, source_kind, name)
            write_adapter(
                claude_path,
                build_adapter(
                    MARKDOWN_HEADER,
                    name=name,
                    description=description,
                    body=body,
                    source_kind=source_kind,
                ),
            )
            generated.append(claude_path)

            cursor_path = root / ".cursor" / "rules" / source_kind / f"{name}.mdc"
            write_adapter(
                cursor_path,
                build_adapter(
                    CURSOR_HEADER,
                    name=name,
                    description=description,
                    body=body,
                    source_kind=source_kind,
                ),
            )
            generated.append(cursor_path)

            codex_path = root / ".codex" / codex_adapter_dir(source_kind) / f"{name}.md"
            write_adapter(
                codex_path,
                build_adapter(
                    MARKDOWN_HEADER,
                    name=name,
                    description=description,
                    body=body,
                    source_kind=source_kind,
                ),
            )
            generated.append(codex_path)

        source_names_by_kind[source_kind] = source_names

    return source_names_by_kind


def remove_generated_file(path: Path, removed: list[Path]) -> None:
    if is_generated(path):
        path.unlink()
        removed.append(path)


def remove_empty_dir(path: Path, removed: list[Path]) -> None:
    if path.exists() and path.is_dir() and not any(path.iterdir()):
        path.rmdir()
        removed.append(path)


def remove_markdown_stale(
    adapter_dir: Path,
    source_names: set[str],
    removed: list[Path],
) -> None:
    if not adapter_dir.exists():
        return
    for adapter_file in adapter_dir.glob("*.md"):
        if adapter_file.stem not in source_names:
            remove_generated_file(adapter_file, removed)
    for adapter_file in adapter_dir.glob("*.mdc"):
        if adapter_file.stem not in source_names:
            remove_generated_file(adapter_file, removed)


def remove_stale_adapters(
    root: Path,
    source_names_by_kind: dict[str, set[str]],
    *,
    removed: list[Path],
) -> None:
    skill_names = source_names_by_kind.get("skills", set())
    claude_skills_dir = root / ".claude" / "skills"
    if claude_skills_dir.exists():
        for legacy_flat_file in claude_skills_dir.glob("*.md"):
            remove_generated_file(legacy_flat_file, removed)

        for skill_dir in claude_skills_dir.iterdir():
            if not skill_dir.is_dir():
                continue
            skill_file = skill_dir / "SKILL.md"
            if skill_dir.name not in skill_names and skill_file.exists():
                remove_generated_file(skill_file, removed)
                remove_empty_dir(skill_dir, removed)

    remove_markdown_stale(root / ".claude" / "agents", source_names_by_kind["roles"], removed)
    remove_markdown_stale(
        root / ".claude" / "workflows",
        source_names_by_kind["workflows"],
        removed,
    )

    remove_markdown_stale(root / ".codex" / "skills", skill_names, removed)
    remove_markdown_stale(root / ".codex" / "agents", source_names_by_kind["roles"], removed)
    remove_markdown_stale(
        root / ".codex" / "workflows",
        source_names_by_kind["workflows"],
        removed,
    )

    cursor_rules_dir = root / ".cursor" / "rules"
    if cursor_rules_dir.exists():
        for legacy_skill_file in cursor_rules_dir.glob("*.mdc"):
            remove_generated_file(legacy_skill_file, removed)

    remove_markdown_stale(root / ".cursor" / "rules" / "skills", skill_names, removed)
    remove_markdown_stale(
        root / ".cursor" / "rules" / "roles",
        source_names_by_kind["roles"],
        removed,
    )
    remove_markdown_stale(
        root / ".cursor" / "rules" / "workflows",
        source_names_by_kind["workflows"],
        removed,
    )


def sync(root: Path | None = None) -> int:
    root = root or ROOT
    generated: list[Path] = []
    removed: list[Path] = []

    source_names_by_kind = generate_adapters(root, generated=generated)
    remove_stale_adapters(root, source_names_by_kind, removed=removed)

    total_sources = sum(len(names) for names in source_names_by_kind.values())
    print(f"synced {total_sources} canonical instruction file(s)")
    for source_kind, names in source_names_by_kind.items():
        print(f"  {source_kind}: {len(names)}")
    print(f"  generated {len(generated)} adapter(s)")
    for path in sorted(generated, key=lambda p: str(p.relative_to(root))):
        print(f"    + {path.relative_to(root)}")

    if removed:
        print(f"  removed {len(removed)} stale adapter(s)")
        for path in sorted(removed, key=lambda p: str(p.relative_to(root))):
            print(f"    - {path.relative_to(root)}")

    print("targets:")
    print("  .claude/skills/<name>/SKILL.md")
    print("  .claude/agents/<name>.md")
    print("  .claude/workflows/<name>.md")
    print("  .cursor/rules/skills/<name>.mdc")
    print("  .cursor/rules/roles/<name>.mdc")
    print("  .cursor/rules/workflows/<name>.mdc")
    print("  .codex/skills/<name>.md")
    print("  .codex/agents/<name>.md")
    print("  .codex/workflows/<name>.md")

    return 0


if __name__ == "__main__":
    sys.exit(sync())
